### ISSUE TITLE
Language-File

### ISSUE THREAD

**Issue by IGELGAMES** [Aaron2550/LCP#1]
A editable language file would be nice :)

**Comment by Aaron2550** [comment]
👍




<sub>I'm gonna be lazy and not support multiple languages at once tho...</sub>

**Comment by Aaron2550** [comment]
It's done! https://modrinth.com/plugin/lode-claims-plugin/version/JHy9PgK6

Feel free to make a new issue if you find any problems. I tested it on a 1.19.4 pufferfish server and it worked just fine!
